trigger:
  - master

# Set variables once
variables:
  linux: 'ubuntu-16.04'
  mac: 'macos-10.13'
  windows: 'vs2017-win2016'

pr:
  branches:
    include:
      - '*'

jobs:
  - job: 'Test'
    strategy:
      matrix:
        py27-linux:
          imageName: $(linux)
          python.version: '2.7'
          tox.env: py27
        py35-linux:
          imageName: $(linux)
          python.version: '3.5'
          tox.env: py35
        py36-linux:
          imageName: $(linux)
          python.version: '3.6'
          tox.env: py36
        py37-linux:
          imageName: $(linux)
          python.version: '3.7'
          tox.env: py37
        py27-mac:
          imageName: $(mac)
          python.version: '2.7'
          tox.env: py27
        py35-mac:
          imageName: $(mac)
          python.version: '3.5'
          tox.env: py35
        py36-mac:
          imageName: $(mac)
          python.version: '3.6'
          tox.env: py36
        py37-mac:
          imageName: $(mac)
          python.version: '3.7'
          tox.env: py37
        py27-win:
          imageName: $(windows)
          python.version: '2.7'
          tox.env: py27
        py35-win:
          imageName: $(windows)
          python.version: '3.5'
          tox.env: py35
        py36-win:
          imageName: $(windows)
          python.version: '3.6'
          tox.env: py36
        py37-win:
          imageName: $(windows)
          python.version: '3.7'
          tox.env: py37
        flake8:
          imageName: $(linux)
          python.version: '3.6'
          tox.env: flake8
        dist:
          imageName: $(linux)
          python.version: '3.6'
          tox.env: dist
        docs:
          imageName: $(linux)
          python.version: '3.6'
          tox.env: docs
        manifest:
          imageName: $(linux)
          python.version: '3.6'
          tox.env: manifest

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version) for tests'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install -U pip
      displayName: 'Upgrade pip'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e $(tox.env)
      displayName: 'Run tox -e $(tox.env)'
